// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNote(arg1, arg2) {
  return window['go']['main']['ModelController']['AddNote'](arg1, arg2);
}

export function Count() {
  return window['go']['main']['ModelController']['Count']();
}

export function CreateTask(arg1) {
  return window['go']['main']['ModelController']['CreateTask'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['ModelController']['DeleteNote'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['ModelController']['DeleteTask'](arg1);
}

export function DeleteTimeEntry(arg1) {
  return window['go']['main']['ModelController']['DeleteTimeEntry'](arg1);
}

export function Export() {
  return window['go']['main']['ModelController']['Export']();
}

export function GetAllTasks() {
  return window['go']['main']['ModelController']['GetAllTasks']();
}

export function GetSummaryForEntries(arg1) {
  return window['go']['main']['ModelController']['GetSummaryForEntries'](arg1);
}

export function GetTaskByID(arg1) {
  return window['go']['main']['ModelController']['GetTaskByID'](arg1);
}

export function GetTaskNoteCount(arg1) {
  return window['go']['main']['ModelController']['GetTaskNoteCount'](arg1);
}

export function GetTaskNotes(arg1) {
  return window['go']['main']['ModelController']['GetTaskNotes'](arg1);
}

export function GetTimeEntriesForWeek() {
  return window['go']['main']['ModelController']['GetTimeEntriesForWeek']();
}

export function GetTimeEntriesToday() {
  return window['go']['main']['ModelController']['GetTimeEntriesToday']();
}

export function GetTrackedTaskDetails() {
  return window['go']['main']['ModelController']['GetTrackedTaskDetails']();
}

export function Import(arg1) {
  return window['go']['main']['ModelController']['Import'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['ModelController']['StartTask'](arg1);
}

export function StopTask() {
  return window['go']['main']['ModelController']['StopTask']();
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['ModelController']['UpdateNote'](arg1, arg2);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['ModelController']['UpdateTask'](arg1, arg2);
}

export function UpdateTimeEntry(arg1, arg2) {
  return window['go']['main']['ModelController']['UpdateTimeEntry'](arg1, arg2);
}
