// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Count():Promise<number>;

export function CreateTask(arg1:main.Task):Promise<main.Task>;

export function DeleteTask(arg1:number):Promise<Error>;

export function GetAllTasks():Promise<Array<main.Task>>;

export function GetTaskByID(arg1:number):Promise<main.Task>;

export function UpdateTask(arg1:number,arg2:main.Task):Promise<main.Task>;
