// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Count() {
  return ObfuscatedCall(5, []);
}

export function CreateTask(arg1) {
  return ObfuscatedCall(6, [arg1]);
}

export function DeleteTask(arg1) {
  return ObfuscatedCall(7, [arg1]);
}

export function Export() {
  return ObfuscatedCall(8, []);
}

export function GetAllTasks() {
  return ObfuscatedCall(9, []);
}

export function GetTaskByID(arg1) {
  return ObfuscatedCall(10, [arg1]);
}

export function Import(arg1) {
  return ObfuscatedCall(11, [arg1]);
}

export function UpdateTask(arg1, arg2) {
  return ObfuscatedCall(12, [arg1, arg2]);
}
