// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Count() {
  return window['go']['main']['TaskController']['Count']();
}

export function CreateTask(arg1) {
  return window['go']['main']['TaskController']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['TaskController']['DeleteTask'](arg1);
}

export function Export() {
  return window['go']['main']['TaskController']['Export']();
}

export function GetAllTasks() {
  return window['go']['main']['TaskController']['GetAllTasks']();
}

export function GetSummaryForEntries(arg1) {
  return window['go']['main']['TaskController']['GetSummaryForEntries'](arg1);
}

export function GetTaskByID(arg1) {
  return window['go']['main']['TaskController']['GetTaskByID'](arg1);
}

export function GetTimeEntriesForWeek() {
  return window['go']['main']['TaskController']['GetTimeEntriesForWeek']();
}

export function GetTimeEntriesToday() {
  return window['go']['main']['TaskController']['GetTimeEntriesToday']();
}

export function GetTrackedTaskDetails() {
  return window['go']['main']['TaskController']['GetTrackedTaskDetails']();
}

export function Import(arg1) {
  return window['go']['main']['TaskController']['Import'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['TaskController']['StartTask'](arg1);
}

export function StopTask() {
  return window['go']['main']['TaskController']['StopTask']();
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['TaskController']['UpdateTask'](arg1, arg2);
}
