// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {func(bolthold} from '../models';

export function Count():Promise<number>;

export function CreateTask(arg1:data.Task):Promise<data.Task>;

export function DeleteTask(arg1:number):Promise<Error>;

export function Export():Promise<string>;

export function GetAllTasks():Promise<Array<data.Task>>;

export function GetTaskByID(arg1:number):Promise<data.Task>;

export function GetTimeEntries(arg1:Array<func(bolthold.Query)>):Promise<Array<data.TimeEntry>>;

export function Import(arg1:string):Promise<Error>;

export function StartTask(arg1:number):Promise<Error>;

export function StopTask():Promise<Error>;

export function UpdateTask(arg1:number,arg2:data.Task):Promise<data.Task>;
