// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function DebugEvent(arg1:string,arg2:Array<any>):Promise<void>;

export function ErrorEvent(arg1:string,arg2:Array<any>):Promise<void>;

export function InfoEvent(arg1:string,arg2:Array<any>):Promise<void>;

export function LogEventName():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function WarnEvent(arg1:string,arg2:Array<any>):Promise<void>;
