// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugEvent(arg1, arg2) {
  return ObfuscatedCall(0, [arg1, arg2]);
}

export function ErrorEvent(arg1, arg2) {
  return ObfuscatedCall(1, [arg1, arg2]);
}

export function InfoEvent(arg1, arg2) {
  return ObfuscatedCall(2, [arg1, arg2]);
}

export function LogEventName() {
  return ObfuscatedCall(3, []);
}

export function WarnEvent(arg1, arg2) {
  return ObfuscatedCall(4, [arg1, arg2]);
}
