// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugEvent(arg1, arg2) {
  return window['go']['eventlog']['EventLog']['DebugEvent'](arg1, arg2);
}

export function ErrorEvent(arg1, arg2) {
  return window['go']['eventlog']['EventLog']['ErrorEvent'](arg1, arg2);
}

export function InfoEvent(arg1, arg2) {
  return window['go']['eventlog']['EventLog']['InfoEvent'](arg1, arg2);
}

export function LogEventName() {
  return window['go']['eventlog']['EventLog']['LogEventName']();
}

export function SetDebug(arg1) {
  return window['go']['eventlog']['EventLog']['SetDebug'](arg1);
}

export function WarnEvent(arg1, arg2) {
  return window['go']['eventlog']['EventLog']['WarnEvent'](arg1, arg2);
}
